// APP ACTIONS
export const FETCH_FIRE_SUCCESS = 'FETCH_FIRE_SUCCESS'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_CLIENT = 'SET_CLIENT'
export const TOGGLE_CHECK = 'TOGGLE_CHECK'
export const ADD_TO_LIST_SUCCESS = 'ADD_TO_LIST_SUCCESS'
export const TRASH_USER = 'TRASH_USER'
export const ON_FILTER = 'ON_FILTER'

// MENU ACTION
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

// ERROR ACTIONS
export const GOT_ERROR = 'GOT_ERROR'
